### ISSUE TITLE
Registry. Kubernetes. Concurrent requests to k8s api takes a too much time

### ISSUE THREAD

**Issue by saromanov** [micro/go-plugins#111]
**Preamble**
We using a Kubernetes Registry Plugin+Google Container Engine and current flow is: service A sending RPC request via  function _B_Method_ to the service B. At the inner it calls "GetService" method

https://github.com/micro/go-plugins/blob/master/registry/kubernetes/kubernetes.go#L137

which calls k8s api for getting list of the Pods. 
**Problem**
This flow working fine with a sequential requests, but if number of requests is a huge and such requests is concurrent, response from api takes 5-10 seconds!

We tried to add a trivial caches for GetService method, and it was a helpful(requests takes 200-300 ms), but of course, is a useless for the real world, because its a LOCAL cache.

This is exist a way for fix such a huge time for response from api?

**Comment by asim** [comment]
This is what the [selector/cache](https://github.com/micro/go-micro/blob/master/selector/cache/cache.go) is for. Use the selector cache with --selector=cache. Each service will maintain a local cache of services its making requests to.

Otherwise write a kubernetes registry that offloads load balancing to kubernetes services instead of doing the API lookup for pods.

**Comment by asim** [comment]
No response in 1 week. Closing.
