### ISSUE TITLE
No way to check rabbitmq connection error

### ISSUE THREAD

**Issue by DexterHD** [micro/go-plugins#114]
There is problem with [rabbitmq broker](https://github.com/micro/go-plugins/blob/master/broker/rabbitmq/rabbitmq.go#L139) implementation, because it never returns an connection error. But another types of broker like `redis` or `kafka` return error well.

```go
func (r *rbroker) Connect() error {
	<-r.conn.Init(r.opts.Secure, r.opts.TLSConfig)
	return nil
}
```
So if there is an error, my service get stuck and there is no way to check if connection was success or not. Also there is no way to stop my service, if there is not connection to broker or configuration is bad.

To do so I need to write my own function like this, but I think there is wrong way:

```go
func checkRabbitConnection(address string) {
	conn, err := amqp.Dial(address)
	defer conn.Close()
	if err != nil {
		log.Fatalf("Can't connect to RabbitMQ server: %s", err)
	}
}
```

**Comment by asim** [comment]
Just to let you know, I've seen your issue but do not have a solution yet. I'll get back to you when I do.

**Comment by asim** [comment]
I have updated the broker code so that connect will return an error if there's a connection failure https://github.com/micro/go-plugins/commit/4e08ca5c3f8d90a179a87789a9ca6511947bfafd. There is still some reconnection logic which requires resubscription if the connection is lost but I'll work on that separately.

**Comment by DexterHD** [comment]
Thanks, at this moment it's enough.
