### ISSUE TITLE
How to check if a service subcribe to other service ?

### ISSUE THREAD

**Issue by long25vn** [micro/go-plugins#195]
I have two services,  A and B. Service A publish message and service B subscribe to service A. 
How can service A check if service B subscribe successfully. I used Nats plugin

```
        broker := nats.NewBroker()
	service := micro.NewService(
		micro.Broker(broker),
		micro.RegisterTTL(time.Second*30),
		micro.RegisterInterval(time.Second*10),
	)

	service.Init()
	micro.RegisterSubscriber("publish-event", service.Server(), new(Sub))
	proto.RegisterLogsHandler(service.Server(), logs)
```

**Comment by asim** [comment]
This is something you have to manually deal with because async messaging has no guarantees. The whole idea being asynchronous messaging is to decouple the publisher from the subscriber. If you need Service A to acknowledge the subscription by Service B then you should either use RPC or you should implement a callback.
