### ISSUE TITLE
kubernetes register services remotely

### ISSUE THREAD

**Issue by magaldima** [micro/go-plugins#197]
Currently the `kubernetes` registry plugin allows you to use it to register services via adding/remove labels for the specific pod you are running on. I'm proposing an alternative kubernetes registry to allow you to register/deregister services remotely or in other words from a different pod/container/process. 

I'm not exactly sure how this would look since I am fairly new to micro. It would be nice if these could be managed through `micro service CRDs`, however then it would introduce an external dependency on a `micro-service-controller`.

Thoughts?

**Comment by asim** [comment]
This is something that will require some discussion. It's unclear how we actually do this right now. If there's a need to register/deregister remotely then it changes the underlying assumptions about how we store service information. We currently store it in the pod annotations because if the service goes away it will be removed cleanly. Doing it with CRDs would essentially mean we would separately store and cleanup service information.

I think it might be interesting for someone to implement this as a feature of the registry but I personally do not have the time right now to do it. So if you'd like to do it I welcome the contribution.

**Comment by asim** [comment]
Closing for time being.
