### ISSUE TITLE
kubernetes registry ListServices only returns names

### ISSUE THREAD

**Issue by magaldima** [micro/go-plugins#206]
I am attempting to retrieve the service metadata from a call to `ListServices` from the kubernetes registry. I need access to the metadata of the service for filtering available services for my client.

We're already decoding the annotation, it seems fairly easy then to just return this decoded service.

**Comment by asim** [comment]
ListServices does exactly what it says, it lists the services by name. The problem with providing the data for all services back in this request is that it doesn't scale. Imagine 1000 services. There's currently no implementation for filtering, paging, limiting returned output. It would also require changing the implementation across every registry plugin we support.

Unfortunately I know it's not the answer you're looking for but we need an elegant solution if we were to support it. Otherwise I think it makes sense not to. It's a bit like listing keys out of a key-value store. You wouldn't want all the data returned.

**Comment by asim** [comment]
This is potentially doable but it goes back to whether or not we can support it across all implementations of the registry. In some cases when we list something we only get back names. Not opposed to adding in the functionality though as long as people are aware the filter will fail in certain cases.

Just be aware. Adding an option to the registry would break the interface and require all implementations to be updated. We'd also need all implementations to support the additional features.

**Comment by asim** [comment]
Going to close as we came to an agreement on the way around this for the time being.
