### ISSUE TITLE
What is the difference when setting transport=grpc vs. client=grpc

### ISSUE THREAD

**Issue by aclisp** [micro/go-plugins#220]
Should I set them the same both? From [Micro gRPC](https://github.com/micro/go-grpc), it just set client=grpc, but leave transport untouched. So setting a client will overwrite the transport, right?

**Comment by asim** [comment]
Because grpc is a tightly coupled framework and protocol its hard for us to extract into our abstractions. So with the client we use the grpc-go framework which means it ignores our transport. There's a separate grpc transport for go-micro plugins which uses grpc as the transport but packages the request in  specific proto. For most cases you likely want the client.

**Comment by aclisp** [comment]
Got it.
